<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Extensions.DeviceDetector" Version="1.0.3" />
    <PackageReference Include="GoogleAuthenticator" Version="3.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.3" />
	<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
	<PackageReference Include="FluentValidation" Version="11.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Extensions.Stores\CusstomAuth.Store\CusstomAuth.Store.csproj" />
  </ItemGroup>

</Project>
